### ISSUE TITLE
Where's a version that can run XP?

### ISSUE THREAD

**Issue by hello-smile6** [Pixelsuft/v86-wasmless#1]
I want to use my Windows XP disk image.

**Comment by Pixelsuft** [comment]
This can
![image1](https://user-images.githubusercontent.com/68371847/177042244-db1430f3-c337-4202-908e-59f825a89aa0.png)
![image2](https://user-images.githubusercontent.com/68371847/177042433-0867634a-797d-49ce-8e94-1d4077b80ce1.png)
![image3](https://user-images.githubusercontent.com/68371847/177042573-3e37532b-8d0f-4906-9061-60f2cb6e632e.png)
